- name: install lmd cp
  template:
    dest: /tmp/lmd/install-lmd.sh
    src: install-lmd.sh
    mode: 0644
- name: lmd compose cp
  copy:
    dest: {{ lmdprojectpath }}
    src: lmd
- name: install driver
  shell:
    cmd: bash /tmp/lmd/install-lmd.sh